name: Deploy to Render

on:
  workflow_dispatch:        # Manual trigger from GitHub UI
 # schedule:
  #  - cron: '0 23 * * *'     # Midnight UK time (23:00 UTC)

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Deploy
        run: |
          curl -X POST https://api.render.com/deploy/srv-d09nnj6uk2gs73dncbog?key=xbeVsm8LIbc

